// web/src/components/Tokens.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { api, type ApiToken, type Account } from '../api';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { useToast } from '../composables/useToast';

const { show: toast } = useToast();

/** 令牌列表 */
const tokens = ref<ApiToken[]>([]);
/** 所有账号（用于选择可用/不可用账号） */
const allAccounts = ref<Account[]>([]);
/** 表单弹窗是否可见 */
const showForm = ref(false);
/** 删除确认弹窗 */
const showDeleteConfirm = ref(false);
/** 待删除令牌 ID */
const deleteTargetId = ref<number | null>(null);
/** 当前编辑的令牌 */
const editing = ref<ApiToken | null>(null);
/** 表单数据 */
const form = ref({ name: '', allowed_accounts: '', blocked_accounts: '', concurrency: 0, expires_at: '' });

/** ISO 字符串 → datetime-local 输入值（本地时区） */
function isoToLocalInput(iso?: string | null): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return '';
  const off = d.getTimezoneOffset() * 60000;
  return new Date(d.getTime() - off).toISOString().slice(0, 16);
}

/** datetime-local 输入值 → RFC3339（带时区），空串返回 null */
function localInputToIso(v: string): string | null {
  if (!v) return null;
  const d = new Date(v);
  return isNaN(d.getTime()) ? null : d.toISOString();
}
/** 已复制的令牌 ID */
const copiedId = ref<number | null>(null);

/** 加载令牌列表 */
async function load() {
  try {
    const res = await api.listTokens(1, 100);
    tokens.value = res.data ?? [];
  } catch {
    tokens.value = [];
  }
}

/** 加载所有账号 */
async function loadAccounts() {
  try {
    const res = await api.listAccounts(1, 100);
    allAccounts.value = res.data ?? [];
  } catch {
    allAccounts.value = [];
  }
}

onMounted(() => {
  load();
  loadAccounts();
});

/** 打开新建令牌弹窗 */
function openCreate() {
  editing.value = null;
  form.value = { name: '', allowed_accounts: '', blocked_accounts: '', concurrency: 0, expires_at: '' };
  showForm.value = true;
}

/**
 * 打开编辑令牌弹窗
 * @param t 要编辑的令牌
 */
function openEdit(t: ApiToken) {
  editing.value = t;
  form.value = {
    name: t.name,
    allowed_accounts: t.allowed_accounts,
    blocked_accounts: t.blocked_accounts,
    concurrency: t.concurrency ?? 0,
    expires_at: isoToLocalInput(t.expires_at),
  };
  showForm.value = true;
}

/** 保存令牌 */
async function save() {
  try {
    if (editing.value) {
      await api.updateToken(editing.value.id, {
        name: form.value.name,
        allowed_accounts: form.value.allowed_accounts,
        blocked_accounts: form.value.blocked_accounts,
        concurrency: Number(form.value.concurrency) || 0,
        expires_at: localInputToIso(form.value.expires_at),
      });
    } else {
      await api.createToken({
        name: form.value.name,
        allowed_accounts: form.value.allowed_accounts,
        blocked_accounts: form.value.blocked_accounts,
        concurrency: Number(form.value.concurrency) || 0,
        expires_at: localInputToIso(form.value.expires_at),
      });
    }
    showForm.value = false;
    await load();
  } catch (e: unknown) {
    toast((e as Error).message || '保存失败');
  }
}

/** 确认删除 */
function confirmDelete(id: number) {
  deleteTargetId.value = id;
  showDeleteConfirm.value = true;
}

/** 执行删除 */
async function executeDelete() {
  if (deleteTargetId.value === null) return;
  try {
    await api.deleteToken(deleteTargetId.value);
    showDeleteConfirm.value = false;
    deleteTargetId.value = null;
    await load();
  } catch (e: unknown) {
    toast((e as Error).message || '删除失败');
  }
}

/** 切换令牌状态 */
async function toggleStatus(t: ApiToken) {
  try {
    const newStatus = t.status === 'active' ? 'disabled' : 'active';
    await api.updateToken(t.id, { status: newStatus });
    await load();
  } catch (e: unknown) {
    toast((e as Error).message || '操作失败');
  }
}

/**
 * 复制令牌到剪贴板
 * @param t 令牌对象
 */
async function copyToken(t: ApiToken) {
  if (navigator.clipboard) {
    await navigator.clipboard.writeText(t.token);
  } else {
    const ta = document.createElement('textarea');
    ta.value = t.token;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
  }
  copiedId.value = t.id;
  setTimeout(() => { copiedId.value = null; }, 2000);
}

/**
 * 遮蔽令牌显示
 * @param token 令牌值
 */
function maskToken(token: string): string {
  if (token.length <= 12) return token;
  return token.slice(0, 7) + '...' + token.slice(-4);
}

/**
 * 解析 ID 列表为账号名显示
 * @param ids 逗号分隔的 ID
 */
function formatAccountIds(ids: string): string {
  if (!ids) return '不限制';
  return ids.split(',').map(id => {
    const acc = allAccounts.value.find(a => a.id === Number(id.trim()));
    return acc ? (acc.name || acc.email) : `#${id.trim()}`;
  }).join(', ');
}

/**
 * 获取状态徽章样式
 * @param status 令牌状态
 */
function statusStyle(status: string): { class: string; label: string } {
  if (status === 'active') return { class: 'bg-emerald-50 text-emerald-700 border-emerald-200', label: '活跃' };
  return { class: 'bg-gray-100 text-gray-500 border-gray-200', label: '停用' };
}

/**
 * 切换账号 ID 在输入框中的选中状态
 * @param field 目标字段
 * @param id 账号 ID
 */
function toggleAccountId(field: 'allowed' | 'blocked', id: number) {
  const key = field === 'allowed' ? 'allowed_accounts' : 'blocked_accounts';
  const ids = form.value[key]
    .split(',')
    .map(s => s.trim())
    .filter(s => s !== '');

  const idx = ids.indexOf(String(id));
  if (idx >= 0) {
    ids.splice(idx, 1);
  } else {
    ids.push(String(id));
  }
  form.value[key] = ids.join(',');
}

/**
 * 判断账号 ID 是否已选中
 * @param field 目标字段
 * @param id 账号 ID
 */
function isAccountSelected(field: 'allowed' | 'blocked', id: number): boolean {
  const key = field === 'allowed' ? 'allowed_accounts' : 'blocked_accounts';
  return form.value[key]
    .split(',')
    .map(s => s.trim())
    .includes(String(id));
}
</script>

<template>
  <div class="space-y-4">
    <!-- 标题栏 -->
    <div class="flex justify-between items-center">
      <h2 class="text-lg font-semibold text-[#29261e]">令牌管理</h2>
      <Button
        @click="openCreate"
        class="bg-[#c4704f] hover:bg-[#b5623f] text-white font-medium rounded-xl transition-all duration-200 hover:shadow-md"
      >
        创建令牌
      </Button>
    </div>

    <!-- 令牌卡片列表 -->
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
      <Card
        v-for="t in tokens"
        :key="t.id"
        class="bg-white border-[#e8e2d9] rounded-xl hover:shadow-md transition-all duration-200 overflow-hidden"
      >
        <div class="p-5 space-y-3">
          <!-- 头部：名称 + 状态 -->
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2 min-w-0">
              <div class="w-8 h-8 rounded-lg bg-[#c4704f]/10 flex items-center justify-center flex-shrink-0">
                <svg class="w-4 h-4 text-[#c4704f]" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                </svg>
              </div>
              <div class="min-w-0">
                <p class="text-sm font-medium text-[#29261e] truncate">{{ t.name || '未命名令牌' }}</p>
                <p class="text-xs text-[#8c8475]">{{ new Date(t.created_at).toLocaleDateString('zh-CN') }}</p>
              </div>
            </div>
            <Badge :class="statusStyle(t.status).class" class="border text-xs font-medium flex-shrink-0">
              {{ statusStyle(t.status).label }}
            </Badge>
          </div>

          <!-- Token 值 -->
          <div class="pt-2 border-t border-[#f0ebe4]">
            <div class="flex items-center gap-2">
              <code class="font-mono text-[11px] text-[#8c8475] truncate flex-1">{{ maskToken(t.token) }}</code>
              <Button
                variant="ghost"
                size="sm"
                @click="copyToken(t)"
                class="h-7 px-2 text-[#8c8475] hover:text-[#29261e] hover:bg-[#f0ebe4] flex-shrink-0"
              >
                {{ copiedId === t.id ? '已复制' : '复制' }}
              </Button>
            </div>
          </div>

          <!-- 账号限制 -->
          <div class="space-y-2">
            <div>
              <p class="text-[10px] text-[#b5b0a6] uppercase tracking-wider mb-0.5">可用账号</p>
              <p class="text-xs text-[#8c8475] truncate">{{ formatAccountIds(t.allowed_accounts) }}</p>
            </div>
            <div>
              <p class="text-[10px] text-[#b5b0a6] uppercase tracking-wider mb-0.5">不可用账号</p>
              <p class="text-xs text-[#8c8475] truncate">{{ formatAccountIds(t.blocked_accounts) }}</p>
            </div>
            <div class="flex gap-4">
              <div class="flex-1">
                <p class="text-[10px] text-[#b5b0a6] uppercase tracking-wider mb-0.5">并发上限</p>
                <p class="text-xs text-[#8c8475] truncate">{{ t.concurrency > 0 ? t.concurrency : '不限制' }}</p>
              </div>
              <div class="flex-1">
                <p class="text-[10px] text-[#b5b0a6] uppercase tracking-wider mb-0.5">过期时间</p>
                <p class="text-xs text-[#8c8475] truncate">
                  {{ t.expires_at ? new Date(t.expires_at).toLocaleString('zh-CN') : '永不过期' }}
                </p>
              </div>
            </div>
          </div>

          <!-- 操作按钮 -->
          <div class="flex items-center gap-2 pt-2 border-t border-[#f0ebe4]">
            <Button
              variant="ghost"
              size="sm"
              @click="openEdit(t)"
              class="text-[#8c8475] hover:text-[#29261e] hover:bg-[#f0ebe4] h-8 px-3 text-xs flex-1"
            >
              编辑
            </Button>
            <Button
              variant="ghost"
              size="sm"
              @click="toggleStatus(t)"
              class="h-8 px-3 text-xs flex-1"
              :class="t.status === 'active'
                ? 'text-[#8c8475] hover:text-[#29261e] hover:bg-[#f0ebe4]'
                : 'text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50'"
            >
              {{ t.status === 'active' ? '停用' : '启用' }}
            </Button>
            <Button
              variant="ghost"
              size="sm"
              @click="confirmDelete(t.id)"
              class="text-red-400 hover:text-red-500 hover:bg-red-50 h-8 px-3 text-xs flex-1"
            >
              删除
            </Button>
          </div>
        </div>
      </Card>

      <!-- 空状态 -->
      <div
        v-if="tokens.length === 0"
        class="col-span-full flex flex-col items-center justify-center py-16 text-[#b5b0a6]"
      >
        <div class="w-12 h-12 rounded-xl bg-[#f0ebe4] flex items-center justify-center mb-3">
          <svg class="w-6 h-6 text-[#c4704f]/50" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
          </svg>
        </div>
        <p class="text-sm">暂无令牌，点击"创建令牌"开始</p>
      </div>
    </div>

    <!-- 新建/编辑令牌弹窗 -->
    <Dialog v-model:open="showForm">
      <DialogContent class="bg-white border-[#e8e2d9] rounded-2xl text-[#29261e] sm:max-w-md">
        <DialogHeader>
          <DialogTitle class="text-[#29261e] text-lg">{{ editing ? '编辑令牌' : '创建令牌' }}</DialogTitle>
          <DialogDescription class="text-[#8c8475]">
            {{ editing ? '修改令牌设置' : '创建新的 API 令牌，令牌将自动生成' }}
          </DialogDescription>
        </DialogHeader>

        <form @submit.prevent="save" class="space-y-4 mt-2">
          <div class="space-y-2">
            <Label class="text-[#5c5647] text-sm">备注名（选填）</Label>
            <Input
              v-model="form.name"
              placeholder="例如：生产环境、测试用"
              class="bg-[#f9f6f1] border-[#e8e2d9] text-[#29261e] placeholder-[#b5b0a6] focus:border-[#c4704f] focus:ring-[#c4704f]/20"
            />
          </div>
          <div class="space-y-2">
            <Label class="text-[#5c5647] text-sm">可用账号（选填，留空不限制）</Label>
            <Input
              v-model="form.allowed_accounts"
              placeholder="账号 ID，逗号分隔"
              class="bg-[#f9f6f1] border-[#e8e2d9] text-[#29261e] placeholder-[#b5b0a6] focus:border-[#c4704f] focus:ring-[#c4704f]/20"
            />
            <div v-if="allAccounts.length" class="flex flex-wrap gap-1.5">
              <button
                v-for="a in allAccounts"
                :key="a.id"
                type="button"
                @click="toggleAccountId('allowed', a.id)"
                class="text-[10px] px-2 py-0.5 rounded-md border transition-colors"
                :class="isAccountSelected('allowed', a.id)
                  ? 'bg-[#c4704f]/10 border-[#c4704f]/30 text-[#c4704f]'
                  : 'bg-[#f9f6f1] border-[#e8e2d9] text-[#8c8475] hover:border-[#c4704f]/30'"
              >
                #{{ a.id }} {{ a.name || a.email }}
              </button>
            </div>
          </div>
          <div class="space-y-2">
            <Label class="text-[#5c5647] text-sm">不可用账号（选填）</Label>
            <Input
              v-model="form.blocked_accounts"
              placeholder="账号 ID，逗号分隔"
              class="bg-[#f9f6f1] border-[#e8e2d9] text-[#29261e] placeholder-[#b5b0a6] focus:border-[#c4704f] focus:ring-[#c4704f]/20"
            />
            <div v-if="allAccounts.length" class="flex flex-wrap gap-1.5">
              <button
                v-for="a in allAccounts"
                :key="a.id"
                type="button"
                @click="toggleAccountId('blocked', a.id)"
                class="text-[10px] px-2 py-0.5 rounded-md border transition-colors"
                :class="isAccountSelected('blocked', a.id)
                  ? 'bg-red-50 border-red-200 text-red-500'
                  : 'bg-[#f9f6f1] border-[#e8e2d9] text-[#8c8475] hover:border-red-200'"
              >
                #{{ a.id }} {{ a.name || a.email }}
              </button>
            </div>
          </div>

          <div class="grid grid-cols-2 gap-3">
            <div class="space-y-2">
              <Label class="text-[#5c5647] text-sm">并发上限（0=不限）</Label>
              <Input
                v-model.number="form.concurrency"
                type="number"
                min="0"
                placeholder="0"
                class="bg-[#f9f6f1] border-[#e8e2d9] text-[#29261e] placeholder-[#b5b0a6] focus:border-[#c4704f] focus:ring-[#c4704f]/20"
              />
            </div>
            <div class="space-y-2">
              <Label class="text-[#5c5647] text-sm">过期时间（选填）</Label>
              <Input
                v-model="form.expires_at"
                type="datetime-local"
                class="bg-[#f9f6f1] border-[#e8e2d9] text-[#29261e] placeholder-[#b5b0a6] focus:border-[#c4704f] focus:ring-[#c4704f]/20"
              />
            </div>
          </div>

          <DialogFooter class="gap-2 pt-2">
            <Button
              type="button"
              variant="ghost"
              @click="showForm = false"
              class="text-[#8c8475] hover:text-[#29261e] hover:bg-[#f0ebe4]"
            >
              取消
            </Button>
            <Button
              type="submit"
              class="bg-[#c4704f] hover:bg-[#b5623f] text-white font-medium rounded-xl transition-all duration-200"
            >
              保存
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>

    <!-- 删除确认弹窗 -->
    <Dialog v-model:open="showDeleteConfirm">
      <DialogContent class="bg-white border-[#e8e2d9] rounded-2xl text-[#29261e] sm:max-w-sm">
        <DialogHeader>
          <DialogTitle class="text-[#29261e]">确认删除</DialogTitle>
          <DialogDescription class="text-[#8c8475]">
            此操作不可撤销，删除后使用该令牌的客户端将无法访问。
          </DialogDescription>
        </DialogHeader>
        <DialogFooter class="gap-2 pt-4">
          <Button
            variant="ghost"
            @click="showDeleteConfirm = false"
            class="text-[#8c8475] hover:text-[#29261e] hover:bg-[#f0ebe4]"
          >
            取消
          </Button>
          <Button
            @click="executeDelete"
            class="bg-red-500 hover:bg-red-600 text-white font-medium rounded-xl transition-all duration-200"
          >
            删除
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
</template>

// web/src/pages/Tokens.tsx
import { useCallback, useEffect, useState } from 'react';
import { Plus, Copy, Check, KeyRound } from 'lucide-react';
import { api, type ApiToken, type Account } from '@/api';
import { useToast } from '@/components/Toaster';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { BlurFade } from '@/components/magic/blur-fade';

interface TokenForm { name: string; allowed_accounts: string; blocked_accounts: string; concurrency: number; expires_at: string }
const emptyForm = (): TokenForm => ({ name: '', allowed_accounts: '', blocked_accounts: '', concurrency: 0, expires_at: '' });

function isoToLocalInput(iso?: string | null): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return '';
  const off = d.getTimezoneOffset() * 60000;
  return new Date(d.getTime() - off).toISOString().slice(0, 16);
}
function localInputToIso(v: string): string | null {
  if (!v) return null;
  const d = new Date(v);
  return isNaN(d.getTime()) ? null : d.toISOString();
}
function maskToken(token: string): string {
  if (token.length <= 12) return token;
  return token.slice(0, 7) + '...' + token.slice(-4);
}

export default function Tokens() {
  const toast = useToast();
  const [tokens, setTokens] = useState<ApiToken[]>([]);
  const [allAccounts, setAllAccounts] = useState<Account[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<ApiToken | null>(null);
  const [form, setForm] = useState<TokenForm>(emptyForm());
  const [showDelete, setShowDelete] = useState(false);
  const [deleteTargetId, setDeleteTargetId] = useState<number | null>(null);
  const [copiedId, setCopiedId] = useState<number | null>(null);

  const load = useCallback(async () => {
    try { setTokens((await api.listTokens(1, 100)).data ?? []); } catch { setTokens([]); }
  }, []);
  const loadAccounts = useCallback(async () => {
    try { setAllAccounts((await api.listAccounts(1, 100)).data ?? []); } catch { setAllAccounts([]); }
  }, []);
  useEffect(() => { load(); loadAccounts(); }, [load, loadAccounts]);

  const patch = (p: Partial<TokenForm>) => setForm((f) => ({ ...f, ...p }));

  function openCreate() { setEditing(null); setForm(emptyForm()); setShowForm(true); }
  function openEdit(t: ApiToken) {
    setEditing(t);
    setForm({ name: t.name, allowed_accounts: t.allowed_accounts, blocked_accounts: t.blocked_accounts, concurrency: t.concurrency ?? 0, expires_at: isoToLocalInput(t.expires_at) });
    setShowForm(true);
  }

  async function save() {
    try {
      const payload = {
        name: form.name,
        allowed_accounts: form.allowed_accounts,
        blocked_accounts: form.blocked_accounts,
        concurrency: Number(form.concurrency) || 0,
        expires_at: localInputToIso(form.expires_at),
      };
      if (editing) await api.updateToken(editing.id, payload);
      else await api.createToken(payload);
      setShowForm(false);
      await load();
    } catch (e) { toast((e as Error).message || '保存失败'); }
  }

  async function executeDelete() {
    if (deleteTargetId === null) return;
    try {
      await api.deleteToken(deleteTargetId);
      setShowDelete(false); setDeleteTargetId(null); await load();
    } catch (e) { toast((e as Error).message || '删除失败'); }
  }

  async function toggleStatus(t: ApiToken) {
    try { await api.updateToken(t.id, { status: t.status === 'active' ? 'disabled' : 'active' }); await load(); }
    catch (e) { toast((e as Error).message || '操作失败'); }
  }

  async function copyToken(t: ApiToken) {
    try {
      if (navigator.clipboard && window.isSecureContext) await navigator.clipboard.writeText(t.token);
      else {
        const ta = document.createElement('textarea'); ta.value = t.token; ta.style.position = 'fixed'; ta.style.opacity = '0';
        document.body.appendChild(ta); ta.select(); document.execCommand('copy'); document.body.removeChild(ta);
      }
      setCopiedId(t.id); setTimeout(() => setCopiedId(null), 2000);
    } catch { toast('复制失败'); }
  }

  function formatAccountIds(ids: string): string {
    if (!ids) return '不限制';
    return ids.split(',').map((id) => {
      const acc = allAccounts.find((a) => a.id === Number(id.trim()));
      return acc ? (acc.name || acc.email) : `#${id.trim()}`;
    }).join(', ');
  }

  function toggleAccountId(field: 'allowed_accounts' | 'blocked_accounts', id: number) {
    const ids = form[field].split(',').map((s) => s.trim()).filter(Boolean);
    const i = ids.indexOf(String(id));
    if (i >= 0) ids.splice(i, 1); else ids.push(String(id));
    patch({ [field]: ids.join(',') } as Partial<TokenForm>);
  }
  function isSelected(field: 'allowed_accounts' | 'blocked_accounts', id: number) {
    return form[field].split(',').map((s) => s.trim()).includes(String(id));
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-neutral-900">令牌管理</h2>
        <Button onClick={openCreate}><Plus className="h-4 w-4" /> 创建令牌</Button>
      </div>

      <BlurFade>
        <div className="overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-sm">
          <Table>
            <TableHeader>
              <TableRow className="bg-neutral-50/60 hover:bg-transparent">
                <TableHead>令牌</TableHead>
                <TableHead>Token</TableHead>
                <TableHead>可用账号</TableHead>
                <TableHead>不可用账号</TableHead>
                <TableHead>并发</TableHead>
                <TableHead>过期时间</TableHead>
                <TableHead>状态</TableHead>
                <TableHead className="text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {tokens.map((t) => (
                <TableRow key={t.id} className="align-top">
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <div className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600"><KeyRound className="h-3.5 w-3.5" /></div>
                      <div>
                        <p className="text-sm font-medium text-neutral-900">{t.name || '未命名令牌'}</p>
                        <p className="text-xs text-neutral-400">{new Date(t.created_at).toLocaleDateString('zh-CN')}</p>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      <code className="font-mono text-[11px] text-neutral-500">{maskToken(t.token)}</code>
                      <button onClick={() => copyToken(t)} className="text-neutral-400 hover:text-neutral-700" title="复制完整令牌">
                        {copiedId === t.id ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
                      </button>
                    </div>
                  </TableCell>
                  <TableCell className="max-w-[160px] truncate text-xs text-neutral-600" title={formatAccountIds(t.allowed_accounts)}>{formatAccountIds(t.allowed_accounts)}</TableCell>
                  <TableCell className="max-w-[160px] truncate text-xs text-neutral-600" title={formatAccountIds(t.blocked_accounts)}>{formatAccountIds(t.blocked_accounts)}</TableCell>
                  <TableCell className="text-sm text-neutral-700">{t.concurrency > 0 ? t.concurrency : '不限'}</TableCell>
                  <TableCell className="text-xs text-neutral-600">{t.expires_at ? new Date(t.expires_at).toLocaleString('zh-CN') : '永不过期'}</TableCell>
                  <TableCell>
                    <Badge className={t.status === 'active' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-neutral-200 bg-neutral-100 text-neutral-500'}>
                      <span className={cn('h-1.5 w-1.5 rounded-full', t.status === 'active' ? 'bg-emerald-500' : 'bg-neutral-400')} />
                      {t.status === 'active' ? '活跃' : '停用'}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center justify-end gap-0.5">
                      <Button variant="ghost" size="sm" onClick={() => openEdit(t)} className="h-7 px-2 text-xs text-neutral-500">编辑</Button>
                      <Button variant="ghost" size="sm" onClick={() => toggleStatus(t)} className={cn('h-7 px-2 text-xs', t.status === 'active' ? 'text-amber-600 hover:bg-amber-50' : 'text-emerald-600 hover:bg-emerald-50')}>
                        {t.status === 'active' ? '停用' : '启用'}
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => { setDeleteTargetId(t.id); setShowDelete(true); }} className="h-7 px-2 text-xs text-red-500 hover:bg-red-50">删除</Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {tokens.length === 0 && (
                <TableRow className="border-0 hover:bg-transparent">
                  <TableCell colSpan={8} className="py-16">
                    <div className="flex flex-col items-center justify-center text-neutral-400">
                      <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-neutral-100"><KeyRound className="h-6 w-6 text-indigo-400" /></div>
                      <p className="text-sm">暂无令牌，点击"创建令牌"开始</p>
                    </div>
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      </BlurFade>

      {/* 新建/编辑令牌 */}
      <Dialog open={showForm} onOpenChange={setShowForm}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{editing ? '编辑令牌' : '创建令牌'}</DialogTitle>
            <DialogDescription>{editing ? '修改令牌设置' : '创建新的 API 令牌，令牌将自动生成'}</DialogDescription>
          </DialogHeader>
          <form onSubmit={(e) => { e.preventDefault(); save(); }} className="mt-1 space-y-4">
            <div className="space-y-2">
              <Label>备注名（选填）</Label>
              <Input value={form.name} onChange={(e) => patch({ name: e.target.value })} placeholder="例如：生产环境、测试用" />
            </div>
            <div className="space-y-2">
              <Label>可用账号（选填，留空不限制）</Label>
              <Input value={form.allowed_accounts} onChange={(e) => patch({ allowed_accounts: e.target.value })} placeholder="账号 ID，逗号分隔" />
              {allAccounts.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {allAccounts.map((a) => (
                    <button key={a.id} type="button" onClick={() => toggleAccountId('allowed_accounts', a.id)}
                      className={cn('rounded-md border px-2 py-0.5 text-[10px] transition-colors',
                        isSelected('allowed_accounts', a.id) ? 'border-indigo-300 bg-indigo-50 text-indigo-700' : 'border-neutral-200 bg-neutral-50 text-neutral-500 hover:border-indigo-300')}>
                      #{a.id} {a.name || a.email}
                    </button>
                  ))}
                </div>
              )}
            </div>
            <div className="space-y-2">
              <Label>不可用账号（选填）</Label>
              <Input value={form.blocked_accounts} onChange={(e) => patch({ blocked_accounts: e.target.value })} placeholder="账号 ID，逗号分隔" />
              {allAccounts.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {allAccounts.map((a) => (
                    <button key={a.id} type="button" onClick={() => toggleAccountId('blocked_accounts', a.id)}
                      className={cn('rounded-md border px-2 py-0.5 text-[10px] transition-colors',
                        isSelected('blocked_accounts', a.id) ? 'border-red-200 bg-red-50 text-red-500' : 'border-neutral-200 bg-neutral-50 text-neutral-500 hover:border-red-200')}>
                      #{a.id} {a.name || a.email}
                    </button>
                  ))}
                </div>
              )}
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-2">
                <Label>并发上限（0=不限）</Label>
                <Input type="number" min={0} value={form.concurrency} onChange={(e) => patch({ concurrency: Number(e.target.value) })} placeholder="0" />
              </div>
              <div className="space-y-2">
                <Label>过期时间（选填）</Label>
                <Input type="datetime-local" value={form.expires_at} onChange={(e) => patch({ expires_at: e.target.value })} />
              </div>
            </div>
            <DialogFooter className="gap-2 pt-2">
              <Button type="button" variant="ghost" onClick={() => setShowForm(false)}>取消</Button>
              <Button type="submit">保存</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* 删除确认 */}
      <Dialog open={showDelete} onOpenChange={setShowDelete}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader>
            <DialogTitle>确认删除</DialogTitle>
            <DialogDescription>此操作不可撤销，删除后使用该令牌的客户端将无法访问。</DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 pt-2">
            <Button variant="ghost" onClick={() => setShowDelete(false)}>取消</Button>
            <Button className="bg-red-500 text-white hover:bg-red-600" onClick={executeDelete}>删除</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
